const CACHE_NAME="dc-profile-offline-perfil-profile-ms54txmo-uao4vt-digital-invita-2026-07-30t21-21-57-437z-2026-07-28t21-28-54";
const PRECACHE=[
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./favicon.ico",
  "./favicon.ico",
  "./assets/images/avatar-placeholder.svg",
  "./assets/images/cover-placeholder.svg",
  "./assets/images/promo-placeholder.svg",
  "./assets/logos/digital-connect-logo.png",
  "./assets/logos/logo-placeholder.svg",
  "./assets/icons/Catalogo.png",
  "./assets/icons/Correo.png",
  "./assets/icons/Cotizar.png",
  "./assets/icons/Facebook.png",
  "./assets/icons/Guardar contacto.png",
  "./assets/icons/Instagram.png",
  "./assets/icons/LinkedIn.png",
  "./assets/icons/Llamar.png",
  "./assets/icons/Menu y precios.png",
  "./assets/icons/Personalizado.png",
  "./assets/icons/Portafolio.png",
  "./assets/icons/Reservar cita.png",
  "./assets/icons/Sitio web.png",
  "./assets/icons/Telegram.png",
  "./assets/icons/Threads.png",
  "./assets/icons/TikTok.png",
  "./assets/icons/Ubicacion.png",
  "./assets/icons/WhatsApp.png",
  "./assets/icons/X.png",
  "./assets/icons/YouTube.png",
  "./assets/icons/briefcase.svg",
  "./assets/icons/calendar.svg",
  "./assets/icons/catalog.svg",
  "./assets/icons/chevron-right.svg",
  "./assets/icons/contact.svg",
  "./assets/icons/copy.svg",
  "./assets/icons/download.svg",
  "./assets/icons/facebook.svg",
  "./assets/icons/file-text.svg",
  "./assets/icons/globe.svg",
  "./assets/icons/instagram.svg",
  "./assets/icons/link.svg",
  "./assets/icons/linkedin.svg",
  "./assets/icons/mail.svg",
  "./assets/icons/map-pin.svg",
  "./assets/icons/menu.svg",
  "./assets/icons/phone.svg",
  "./assets/icons/spark.svg",
  "./assets/icons/telegram.svg",
  "./assets/icons/threads.svg",
  "./assets/icons/tiktok.svg",
  "./assets/icons/whatsapp.svg",
  "./assets/icons/x.svg",
  "./assets/icons/youtube.svg"
];
self.addEventListener("install",(event)=>{event.waitUntil(caches.open(CACHE_NAME).then((cache)=>cache.addAll(PRECACHE)).then(()=>self.skipWaiting()))});
self.addEventListener("activate",(event)=>{event.waitUntil(caches.keys().then((keys)=>Promise.all(keys.filter((key)=>key.startsWith("dc-profile-offline-")&&key!==CACHE_NAME).map((key)=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener("fetch",(event)=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==location.origin)return;if(request.mode==="navigate"){event.respondWith(fetch(request).then((response)=>{const copy=response.clone();caches.open(CACHE_NAME).then((cache)=>cache.put("./index.html",copy));return response}).catch(()=>caches.match("./index.html")));return}event.respondWith(caches.match(request).then((cached)=>cached||fetch(request).then((response)=>{if(response&&response.status===200){const copy=response.clone();caches.open(CACHE_NAME).then((cache)=>cache.put(request,copy))}return response}).catch(()=>caches.match("./index.html"))))});